// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Test cralwee', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('Test cralwee', async function() {
    await driver.get("https://crawlee.dev/")
    await driver.manage().window().setRect({ width: 685, height: 921 })
    await driver.findElement(By.css(".navbar__toggle > svg")).click()
    await driver.findElement(By.linkText("API")).click()
    {
      const element = await driver.findElement(By.linkText("API"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".tocCollapsibleButton_TO0P"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    vars["windowHandles"] = await driver.getAllWindowHandles()
    await driver.findElement(By.css("li:nth-child(3) > a > code")).click()
    vars["win3907"] = await waitForWindow(2000)
    vars["root"] = await driver.getWindowHandle()
    await driver.switchTo().window(vars["win3907"])
    await driver.close()
    await driver.switchTo().window(vars["root"])
  })
})